services:
  backend:
    image: asattelmaier/go-session-server:latest
    volumes:
      - type: bind
        source: ./dummy-credentials.json
        target: /credentials.json
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials.json
      - FIRESTORE_EMULATOR_ENABLED=true
      - FIRESTORE_EMULATOR_HOST_PORT=firestore-emulator:9000
      - FIRESTORE_EMULATOR_PROJECT_ID=local-project
      - SECURITY_GUEST_PASSWORD=guest-password
      - SECURITY_JWT_ACCESS_TOKEN_EXPIRATION=86400000
      - SECURITY_JWT_REFRESH_TOKEN_EXPIRATION=604800000
      - SECURITY_JWT_SECRET_KEY=8Gr0MjVACbywAYACtN6o0wl4FKIG4s3F2iOGwMA1BQLKXh5ScLIuun0PgZnZ94vm
      - SPRING_PROFILES_ACTIVE=dev
      - CORS_ALLOWED_ORIGINS=*
      - GNUGO_HOST=gnugo
    depends_on:
      - firestore-emulator
      - gnugo
    networks:
      - test-net

  firestore-emulator:
    image: asattelmaier/firestore-emulator:latest
    volumes:
      - type: bind
        source: ./dummy-credentials.json
        target: /opt/firestore-emulator/credentials.json
    ports:
      - "9000:9000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/firestore-emulator/credentials.json
      - PORT=9000
      - PROJECT_ID=local-project
    networks:
      - test-net

  gnugo:
    image: asattelmaier/gnugo:latest
    ports:
      - "8001:8001"
    networks:
      - test-net

  headless-chrome:
    build:
      context: ..
      dockerfile: docker/chrome/Dockerfile
    container_name: docker-headless-chrome
    # Use host network so Chrome can access Flutter server (localhost:random) 
    # and Backend (localhost:8080) easily on Linux.
    network_mode: host
    shm_size: 2gb
    volumes:
      - /tmp:/tmp
      - ..:/app
    environment:
      - CHROME_ARGS=--no-sandbox --disable-dev-shm-usage --headless --disable-gpu --remote-debugging-port=9222

networks:
  test-net:
